spring:
  application:
    name: test-CTM
  datasource:
    url: jdbc:postgresql://localhost:5432/appdatabase
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jooq:
    sql-dialect: postgres
  liquibase:
    change-log: classpath:db/liquibase/changelogs/master-changelog.yml