spring:
  application:
    name: test-CTM
  datasource:
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
#        для работы из контейнера
    url: jdbc:postgresql://postgres:5432/appdatabase
  jooq:
    sql-dialect: postgres
  liquibase:
    change-log: classpath:db/liquibase/changelogs/master-changelog.yml
    user: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    # для работы из контейнера
    url: jdbc:postgresql://postgres:5432/appdatabase