spring:
  application:
    name: test-CTM
  datasource:
    #    для работы из IDEA
    url: jdbc:postgresql://localhost:5432/appdatabase
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jooq:
    sql-dialect: postgres
  liquibase:
    change-log: classpath:db/liquibase/changelogs/master-changelog.yml
    ## для работы из IDEA
    url: jdbc:postgresql://localhost:5432/appdatabase
    user: postgres
    password: root
    driver-class-name: org.postgresql.Driver
springdoc:
  swagger-ui:
    path: /swagger-ui.html

